services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Web/Dockerfile
    depends_on:
      - keymapping-db
    ports:
      - "5000:5000"
    environment:
        ASPNETCORE_URLS: "http://0.0.0.0:5000"

  frontend:
    image: frontend
    build:
      context: ../MultiDb_Frontend/multidb-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web

  keymapping-db:
    image: postgres:15
    container_name: keymapping-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: KeyMappingDb
    ports:
      - "5432:5432"
    volumes:
      - keymapping-db-data:/var/lib/postgresql/data

  shard-db1:
    image: postgres:15
    container_name: shard-db1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ShardDb1
    ports:
      - "5433:5432"
    volumes:
      - shard-db1-data:/var/lib/postgresql/data

  shard-db2:
    image: postgres:15
    container_name: shard-db2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ShardDb2
    ports:
      - "5434:5432"
    volumes:
      - shard-db2-data:/var/lib/postgresql/data

volumes:
  keymapping-db-data:
  shard-db1-data:
  shard-db2-data:
